version: '3'

services:
  
  proxy:
    image: traefik
    command: --web --docker --docker.watch --docker.domain=localhost --logLevel=DEBUG --entryPoints="Name:http Address::80"
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  
  service1:
    image: jwilder/whoami
    labels:
      - "traefik.backend=service1"
      - "traefik.frontend.rule=PathStrip: /,/coucou"
      - "traefik.port=8000"
      - "traefik.frontend.entryPoints=http"
      
  service2:
    image: jwilder/whoami
    labels:
      - "traefik.backend=service2"
      - "traefik.frontend.rule=PathStrip: /stuff"
      - "traefik.port=8000"
      - "traefik.frontend.entryPoints=http"
  
  